import pandas as pd

ct_colors = pd.Series()

ct_colors['EPI'] = '#e41a1c'
ct_colors['PrE'] = '#377eb8'
ct_colors['TE'] = '#4daf4a'
ct_colors['ICM'] = '#984ea3'
ct_colors['Mes'] = '#fbb463'
ct_colors['Blood'] = '#fccde5'
ct_colors['GermCells'] = '#999999'
ct_colors['Midline'] = '#ffff33'
ct_colors['Endothelial'] = '#a65628'
ct_colors['ExE'] = '#4daf4a'
ct_colors['VE'] = '#377eb8'
ct_colors['exVE'] = '#1f78b4'
ct_colors['YsE'] = '#1f78b4'
ct_colors['emVE'] = '#80b1d3'
ct_colors['ParE'] = '#c3e5f4'
ct_colors['DE'] = '#ea7373'
ct_colors['Ant: Guttube'] = '#e31a65'
ct_colors['Post: Guttube'] = '#9ebcda'
ct_colors['Ant: Mes'] = '#f79d43'
ct_colors['Post: Mes'] = '#efbc8b'
ct_colors['GFP+: Guttube'] = '#377eb8'
ct_colors['GFP-: Guttube'] = '#e41a1c'
ct_colors['GFP-: Mes'] = '#fbb463'
ct_colors['Thyroid'] = '#d5bb67'
ct_colors['Thymus'] = '#4878d0'
ct_colors['Lung'] = '#dc7ec0'
ct_colors['Liver'] = '#d65f5f'
ct_colors['Pancreas'] = '#6acc64'
ct_colors['Small int'] = '#ee854a'
ct_colors['Colon'] = '#956cb4'
